### ISSUE TITLE
Minicli returning uncaught error: class '\CreateController' not found

### ISSUE THREAD

**Issue by walegbenga** [minicli/minicli#2]
`Fatal error: Uncaught Error: Class '\CreateController' not found in C:\Users\use
r pc\Desktop\myapp\vendor\minicli\minicli\lib\Command\CommandNamespace.php:71
Stack trace:
#0 C:\Users\user pc\Desktop\myapp\vendor\minicli\minicli\lib\Command\CommandName
space.php(36): Minicli\Command\CommandNamespace->loadCommandMap('C:\\Users\\user
 p...')
#1 C:\Users\user pc\Desktop\myapp\vendor\minicli\minicli\lib\Command\CommandRegi
stry.php(51): Minicli\Command\CommandNamespace->loadControllers('C:\\Users\\user
 p...')
#2 C:\Users\user pc\Desktop\myapp\vendor\minicli\minicli\lib\Command\CommandRegi
stry.php(40): Minicli\Command\CommandRegistry->registerNamespace('Controller')
#3 C:\Users\user pc\Desktop\myapp\vendor\minicli\minicli\lib\Command\CommandRegi
stry.php(31): Minicli\Command\CommandRegistry->autoloadNamespaces()
#4 C:\Users\user pc\Desktop\myapp\vendor\minicli\minicli\lib\App.php(66): Minicl
i\Command\CommandRegistry->load(Object(Minicli\App))
#5 C:\Users\user pc\Desktop\myapp\vendor\minicli\minicli\lib\App.php(46): Minicl
i\App->loa in C:\Users\user pc\Desktop\myapp\vendor\minicli\minicli\lib\Command\
CommandNamespace.php on line 71
`

**Comment by syntaxseed** [comment]
This might be an outdated issue.

But in case you're still having trouble @walegbenga ... have a look at an example command here:

https://github.com/syntaxseed/minicli-demo/blob/master/app/Command/Hello/DefaultController.php

**Comment by wandersonwhcr** [comment]
I am having this issue too.

@walegbenga this is happening because your "CreateController" must to be inside a PHP defined namespace.

https://github.com/minicli/minicli/blob/master/src/Command/CommandNamespace.php#L76

IMHO searching for "namespace" inside file is not the best solution for that.

Minicli have a required fixed structure, with `/path/to/dir/Commands` and every namespace command must be a child of `Commands` directory, like `/path/to/dir/Commands/Something`, and every command from namespace `Something` must to be inside this directory and finished with `Controller.php`, like `/path/to/dir/Commands/Something/SimpleController.php`.

Maybe we must use the namespace directory name instead of namespace name?

**Comment by wandersonwhcr** [comment]
Something crazy that we can build with PHP:

``php
<?php
// app/Commands/Foo/BarController.php

namespace app/Commands/Foo/Libraries
{
    class Client {}
}

namespace app/Commands/Foo
{
    class BarController {}
}

**Comment by walegbenga** [comment]
@wandersonwhcr Oh thanks it fix it

**Comment by erikaheidi** [comment]
Yep, namespaces are required if you want to use Command Namespaces for the `command subcommand` approach. For simple commands you can also just use a one-file app and use `$app->registerCommand` to set commands using callables. 

closing this issue now!
